name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - "1.21"
          - "1.20"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test
        uses: docker/bake-action@v6
        with:
          source: .
          targets: test
        env:
          GO_VERSION: ${{ matrix.go_version }}
      -
        name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
